### PR TITLE
BZ-1296881: Dashbuilder login page not protected against frame busting (6.4.x)

### PR DESCRIPTION
**Pull request by dgutierr**
Fix + tests

@romartin Can you review and +1 please?

### CODE REVIEW

**Comment by romartin** [comment]
@dgutierr Hi David, I do not have commit access to this repository. Cannot push the merge, let me know when fixed. Thx

**Comment by dgutierr** [comment]
you only need to +1

**Comment by romartin** [comment]
+1

**Comment by dgutierr** [comment]
@csadilek Can you merge please?

**Comment by csadilek** [comment]
6.4.x: c7ce15cde852446098e6aa09e5ac4c5630343142

**Pull request closed without merging**
