### PR TITLE
Added a TomEE assembly which required removing the "final" keyword from RootNode.java

### PR DESCRIPTION
**Pull request by jmutawa**
Hello,

This is to create an Apache TomEE assembly, since the existing ones do not work. Tested working on TomEE 1.7.1 which we use at work.

This is my first ever open source contribution and pull request, so please be kind if I did something too newbie :)

### CODE REVIEW

**Comment by dgutierr** [comment]
I've applied your changes and generate the TomEE dashbuilder distribution. I'm having issues when deploying to TomEE 1.7.1 => http://pastebin.com/kHZuz2Kh

I'm not sure if I missed any steps or what's wrong here. Can you double check the installation please?

**Comment by jmutawa** [comment]
I am not sure, it works fine with me. Could you please build from my branch without merging and see if it is any better?

**Comment by jmutawa** [comment]
Strangely, works fine under Linux but not Windows.

**Comment by jmutawa** [comment]
OK, found out where the issue is: It is not liking the way the Logger is injected in the class org.jboss.dashboard.ui.components.DashboardHandler. 

This class is the only class in the whole code base that injects the Logger like this:
<code>@Inject protected Logger log;</code>

I removed the @Inject in my fork and it worked. You may want to tackle the issue differently depending on your standards.

**Comment by dgutierr** [comment]
Tested & working.

The changes have been merged both on master and on 6.3.x branch so that the new assembly is available in the next 6.3 release.

Thanks a lot for this contribution!

**Pull request closed without merging**
